### ISSUE TITLE
(MatchError) no match of right hand side value: ["ets.lookup(1896538, 1)"] in Timber.Events.ExceptionEvent

### ISSUE THREAD

**Issue by johnhamelink** [timberio/timber-elixir#129] opened 2017-04-06 02:56 UTC
Hey there,

I've noticed the following error occurring regularly in AppSignal. I'm not sure what's causing it but it seems to be related to Timber?

```
2017-04-06T03:49:51.000Z [debug] Submitting AppSignal.Transaction{_gbbfd9vn8rek8}: GenServer Pod.Merchants.Mws.Client.Server terminating
2017-04-06T03:49:51.030Z [error] (MatchError) no match of right hand side value: ["ets.lookup(1806415, 1)"]
2017-04-06T03:49:51.031Z [error] GenServer #PID<0.261.0> terminating
** (stop) {:EXIT, {{:badmatch, ["ets.lookup(1806415, 1)"]}, [{Timber.Events.ExceptionEvent, :do_new, 2, [file: 'lib/timber/events/exception_event.ex', line: 81]}, {Timber.Events.ExceptionEvent, :new, 1, [file: 'lib/timber/events/exception_event.ex', line: 49]}, {Timber.LogEntry, :new, 4, [file: 'lib/timber/log_entry.ex', line: 68]}, {Timber.LoggerBackend, :output_event, 5, [file: 'lib/timber/logger_backend.ex', line: 185]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 533]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 515]}, {:gen_event, :handle_msg, 5, [file: 'gen_event.erl', line: 256]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
Last message: {:gen_event_EXIT, Timber.LoggerBackend, {:EXIT, {{:badmatch, ["ets.lookup(1806415, 1)"]}, [{Timber.Events.ExceptionEvent, :do_new, 2, [file: 'lib/timber/events/exception_event.ex', line: 81]}, {Timber.Events.ExceptionEvent, :new, 1, [file: 'lib/timber/events/exception_event.ex', line: 49]}, {Timber.LogEntry, :new, 4, [file: 'lib/timber/log_entry.ex', line: 68]}, {Timber.LoggerBackend, :output_event, 5, [file: 'lib/timber/logger_backend.ex', line: 185]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 533]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 515]}, {:gen_event, :handle_msg, 5, [file: 'gen_event.erl', line: 256]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}
State: {Logger, Timber.LoggerBackend}
2017-04-06T03:49:51.031Z [error] (MatchError) no match of right hand side value: ["ets.lookup(1806415, 1)"]
2017-04-06T03:49:51.035Z [error] (FunctionClauseError) no function clause matching in Appsignal.ErrorHandler.match_error_format/2
2017-04-06T03:49:51.036Z [error] GenServer #PID<0.723.0> terminating
** (stop) {:EXIT, {{:badmatch, ["ets.lookup(1806415, 1)"]}, [{Timber.Events.ExceptionEvent, :do_new, 2, [file: 'lib/timber/events/exception_event.ex', line: 81]}, {Timber.Events.ExceptionEvent, :new, 1, [file: 'lib/timber/events/exception_event.ex', line: 49]}, {Timber.LogEntry, :new, 4, [file: 'lib/timber/log_entry.ex', line: 68]}, {Timber.LoggerBackend, :output_event, 5, [file: 'lib/timber/logger_backend.ex', line: 185]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 533]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 515]}, {:gen_event, :handle_msg, 5, [file: 'gen_event.erl', line: 256]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
Last message: {:gen_event_EXIT, Timber.LoggerBackend, {:EXIT, {{:badmatch, ["ets.lookup(1806415, 1)"]}, [{Timber.Events.ExceptionEvent, :do_new, 2, [file: 'lib/timber/events/exception_event.ex', line: 81]}, {Timber.Events.ExceptionEvent, :new, 1, [file: 'lib/timber/events/exception_event.ex', line: 49]}, {Timber.LogEntry, :new, 4, [file: 'lib/timber/log_entry.ex', line: 68]}, {Timber.LoggerBackend, :output_event, 5, [file: 'lib/timber/logger_backend.ex', line: 185]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 533]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 515]}, {:gen_event, :handle_msg, 5, [file: 'gen_event.erl', line: 256]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}
State: {Logger, Timber.LoggerBackend}
```

**Comment by DavidAntaramian** [comment] 2017-04-06 03:00
@johnhamelink Looking into this. You're on a `1.x` version correct?

**Comment by johnhamelink** [comment] 2017-04-06 03:11
@DavidAntaramian yep that's right. Should I be on 2.x? I literally started using Timber 12 hours ago.

**Comment by DavidAntaramian** [comment] 2017-04-06 03:24
@johnhamelink 2.x is ready but we haven't announced it yet. It works and it plays a lot nicer with the default `:console` logger.

However, upgrading won't fix the problem you're encountering. To give you an overview of the problem, we're expecting an error log to appear with file references in the stacktrace and this line doesn't have them. That's a bad assumption on our part. I'm trying to think of a short-term fix to get you through, and then I'll slate a longer-term fix for next week.

**Comment by DavidAntaramian** [comment] 2017-04-06 04:01
@johnhamelink Quick update. Going over this with @binarylogic. The problem is that `:ets.lookup/2` is natively implemented, so the error gets reported differently. He's changing the functionality of the exception decoder to handle that properly. I'll update you when it's ready.

**Closed** 2017-04-06 04:25 UTC

**Comment by DavidAntaramian** [comment] 2017-04-06 04:29
@johnhamelink You should be able to update to either `1.1.18` or `2.0.1` to fix the issue. Please let us know if you encounter any more issues

**Comment by johnhamelink** [comment] 2017-04-06 15:54
@DavidAntaramian that seemed to work. Thanks 👍
